title: Sohaib Khan
description: Back End Software Engineer
site_title: '@sohaib13k - Sohaib Khan'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: sohaib13k
# blog_url: https://www.nagekar.com
email: sohaibk13@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 